site_name: Dom-$an

# site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent:  light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary:  light blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # Mengatur font
  font:
    text: Open Sans
    code: JetBrains Mono

  # icon:
    # logo: material/book
  favicon: Images/Modern Gradient D Logo (3).png
  logo: images/Modern Gradient D Logo (3).png

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    # - navigation.footer
    # - navigation.tabs
  

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Fitur
  - attr_list
  # Keyboard
  - pymdownx.keys
# Footer
copyright: Made by Sella Ayunia ❤️ Kelompok 2 | &copy; 2025

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/elok27/panduan-apg